<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:mri="http://www.isotc211.org/namespace/mri/1.0/2014-07-11" xmlns:gex="http://www.isotc211.org/namespace/gex/1.0/2014-07-11" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/" xmlns:echo="http://www.echo.nasa.gov/ingest/schemas/operations/" xmlns:eos="http://earthdata.nasa.gov/schema/eos" xmlns:serf="http://gcmd.gsfc.nasa.gov/xml/serf" xmlns:cw="http://www.ngdc.noaa.gov/metadata/published/xsd/crosswalk.xsd" xmlns:thredds="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0" xmlns:hdf5="http://hdfgroup.org/HDF5/XML/schema/HDF5-File" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:fgdc="http://www.fgdc.gov/metadata/csdgm" version="2.0"><xsl:param name="recordSetPath"></xsl:param><xsl:param name="fileNamePattern"></xsl:param><xsl:output method="text"></xsl:output><xsl:template match="/"><xsl:variable name="xmlFilesSelect" select="concat($recordSetPath, '?select=',$fileNamePattern)"></xsl:variable><xsl:text>{"records": [</xsl:text><xsl:for-each select="collection(iri-to-uri($xmlFilesSelect))"><xsl:call-template name="writeSpirals"></xsl:call-template></xsl:for-each><xsl:text>]}</xsl:text></xsl:template><xsl:template name="writeSpirals"><xsl:if test="position()!=1"><xsl:text>,</xsl:text></xsl:if><xsl:text>{"spirals": [</xsl:text><xsl:text>
{</xsl:text><xsl:text>"title":"Dryad Metadata  Application  Profile - Data Package Module-Required",</xsl:text><xsl:text>"code":"DMAP-DP_Required",</xsl:text><xsl:text>"description":"This portion of the Dryad Application Profile has been developed for the group of data files associated with a given publication, or data package. It has been developed in compliance with the Dublin Core Metadata's Initiative's guidlines, including the Singapore Framework. Dryad stores data underlying scientific publications, with an initial focus on evolution, ecology, and related fileds.",</xsl:text><xsl:text>"maximum":"10",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataPackage/dcterms:type | /dryad:DryadDataFile/dcterms:type)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataFile/dryad:status | /dryad:DryadDataPackage/dryad:status)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:creator | /dryad:DryadDataFile/dcterms:creator | /dryad:DryadDataPackage/dcterms:creator)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataFile/dcterms:dateSubmitted | /dryad:DryadDataFile/dcterms:available | /dryad:DryadDataPackage/dcterms:dateSubmitted | /dryad:DryadDataPackage/dcterms:available)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:issued | /dryad:DryadDataFile/dcterms:available | /dryad:DryadDataPackage/dcterms:available)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:title | /dryad:DryadDataPackage/dcterms:title | /dryad:DryadDataFile/dcterms:title)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:identifier | /dryad:DryadDataPackage/dcterms:identifier | /dryad:DryadDataFile/dcterms:identifier)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataFileDryadDataFile/dcterms:subject | /dryad:DryadDataPackage/dcterms:subject)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:isReferencedBy | /dryad:DryadDataPackage/dcterms:external | /dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataPackage/dcterms:hasPart | /dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'existTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataPackage/dcterms:type) + count(/dryad:DryadDataFile/dcterms:type)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataFile/dryad:status) + count(/dryad:DryadDataPackage/dryad:status)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadPublication/dcterms:creator) + count(/dryad:DryadDataFile/dcterms:creator) + count(/dryad:DryadDataPackage/dcterms:creator)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataFile/dcterms:dateSubmitted) + count(/dryad:DryadDataFile/dcterms:available) + count(/dryad:DryadDataPackage/dcterms:dateSubmitted) + count(/dryad:DryadDataPackage/dcterms:available)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadPublication/dcterms:issued) + count(/dryad:DryadDataFile/dcterms:available) + count(/dryad:DryadDataPackage/dcterms:available)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadPublication/dcterms:title) + count(/dryad:DryadDataPackage/dcterms:title) + count(/dryad:DryadDataFile/dcterms:title)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadPublication/dcterms:identifier) + count(/dryad:DryadDataPackage/dcterms:identifier) + count(/dryad:DryadDataFile/dcterms:identifier)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataFileDryadDataFile/dcterms:subject) + count(/dryad:DryadDataPackage/dcterms:subject)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataPackage/dcterms:reference) + count(/dryad:DryadDataFile/dcterms:isPartOf)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadPublication/dcterms:isReferencedBy) + count(/dryad:DryadDataPackage/dcterms:external) + count(/dryad:DryadDataPackage/dcterms:reference) + count(/dryad:DryadDataPackage/dcterms:hasPart) + count(/dryad:DryadDataFile/dcterms:isPartOf)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'countTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"items" : [
</xsl:text><xsl:text>{
</xsl:text><xsl:text>"name":"Resource Type",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e6409" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataPackage/dcterms:type | /dryad:DryadDataFile/dcterms:type)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e6409)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e6409" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataPackage/dcterms:type | /dryad:DryadDataFile/dcterms:type)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e6409)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:type",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:type)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:type)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:type",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:type)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:type)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"A resource code identifying the type of resource; e.g. dataset, a collection, an application (See MD_ScopeCode) for which the metadata describes."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Metadata Access Constraints",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e5186" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataFile/dryad:status | /dryad:DryadDataPackage/dryad:status)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e5186)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e5186" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataFile/dryad:status | /dryad:DryadDataPackage/dryad:status)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e5186)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dryad:status",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dryad:status)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dryad:status)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dryad:status",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dryad:status)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dryad:status)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Information about any constraints for accessing the data set. This includes any special restrictions, legal prerequisites, limitations and/or warnings on obtaining the data set. Some words that may be used in this field include: Public, In-house, Limited, Additional detailed instructions on how to access the data can be entered in this field."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Author",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e1942" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:creator | /dryad:DryadDataFile/dcterms:creator | /dryad:DryadDataPackage/dcterms:creator)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e1942)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e1942" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:creator | /dryad:DryadDataFile/dcterms:creator | /dryad:DryadDataPackage/dcterms:creator)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e1942)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:creator",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:creator)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:creator)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:creator",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:creator)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:creator)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:creator",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:creator)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:creator)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Author of the cited resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Creation/Revision Date",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e423" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataFile/dcterms:dateSubmitted | /dryad:DryadDataFile/dcterms:available | /dryad:DryadDataPackage/dcterms:dateSubmitted | /dryad:DryadDataPackage/dcterms:available)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e423)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e423" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataFile/dcterms:dateSubmitted | /dryad:DryadDataFile/dcterms:available | /dryad:DryadDataPackage/dcterms:dateSubmitted | /dryad:DryadDataPackage/dcterms:available)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e423)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:dateSubmitted",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:dateSubmitted)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:dateSubmitted)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:available",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:available)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:available)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:dateSubmitted",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:dateSubmitted)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:dateSubmitted)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:available",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:available)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:available)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The date the resource was created"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Publication Date",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e2073" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:issued | /dryad:DryadDataFile/dcterms:available | /dryad:DryadDataPackage/dcterms:available)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e2073)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e2073" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:issued | /dryad:DryadDataFile/dcterms:available | /dryad:DryadDataPackage/dcterms:available)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e2073)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:issued",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:issued)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:issued)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:available",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:available)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:available)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:available",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:available)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:available)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Date of publication of the cited resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Title",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e287" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:title | /dryad:DryadDataPackage/dcterms:title | /dryad:DryadDataFile/dcterms:title)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e287)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e287" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:title | /dryad:DryadDataPackage/dcterms:title | /dryad:DryadDataFile/dcterms:title)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e287)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:title",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:title)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:title)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:title",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:title)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:title)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:title",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:title)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:title)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"A short description of the resource. The title should be descriptive enough so that when a user is presented with a list of titles the general content of the data set can be determined."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Identifier",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e2737" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:identifier | /dryad:DryadDataPackage/dcterms:identifier | /dryad:DryadDataFile/dcterms:identifier)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e2737)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e2737" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:identifier | /dryad:DryadDataPackage/dcterms:identifier | /dryad:DryadDataFile/dcterms:identifier)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e2737)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:identifier",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:identifier)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:identifier)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:identifier",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:identifier)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:identifier)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:identifier",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:identifier)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:identifier)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Identifier for the resource described by the metadata"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Keyword",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e12725" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataFileDryadDataFile/dcterms:subject | /dryad:DryadDataPackage/dcterms:subject)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e12725)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e12725" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataFileDryadDataFile/dcterms:subject | /dryad:DryadDataPackage/dcterms:subject)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e12725)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFileDryadDataFile/dcterms:subject",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFileDryadDataFile/dcterms:subject)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFileDryadDataFile/dcterms:subject)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:subject",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:subject)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:subject)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"A word or phrase that describes some aspect of a resource. Can be one of several types."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Parent Identifier",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e2958" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e2958)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e2958" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataFile/dcterms:isPartOf)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e2958)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:reference",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:reference)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:reference)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:isPartOf",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:isPartOf)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"A unique identifier for a parent dataset or collection"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Related Resource Identifier",</xsl:text><xsl:variable name="DMAP-DP_Required.itemExists.d1e2829" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:isReferencedBy | /dryad:DryadDataPackage/dcterms:external | /dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataPackage/dcterms:hasPart | /dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemExists.d1e2829)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Required.itemCounts.d1e2829" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:isReferencedBy | /dryad:DryadDataPackage/dcterms:external | /dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataPackage/dcterms:hasPart | /dryad:DryadDataFile/dcterms:isPartOf)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Required.itemCounts.d1e2829)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:isReferencedBy",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:isReferencedBy)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:isReferencedBy)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:external",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:external)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:external)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:reference",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:reference)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:reference)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:hasPart",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:hasPart)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:hasPart)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:isPartOf",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:isPartOf)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Identifier for a resource related to the resource being described."</xsl:text><xsl:text>}</xsl:text>
<xsl:text>]
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"title":"Dryad Metadata  Application  Profile - Data Package Module-Optional",</xsl:text><xsl:text>"code":"DMAP-DP_Optional",</xsl:text><xsl:text>"description":"This portion of the Dryad Application Profile has been developed for the group of data files associated with a given publication, or data package. It has been developed in compliance with the Dublin Core Metadata's Initiative's guidlines, including the Singapore Framework. Dryad stores data underlying scientific publications, with an initial focus on evolution, ecology, and related fileds.",</xsl:text><xsl:text>"maximum":"6",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:dabstract | /dryad:DryadDataFile/dcterms:description | /dryad:DryadDataPackage/dcterms:description)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataFile/dwc:scientificName | /dryad:DryadDataPackage/dwc:scientificName)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataFile/dcterms:spatial | /dryad:DryadDataPackage/dcterms:spatial)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataFile/dcterms:temporal | /dryad:*/dcterms:temporal)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:isReferencedBy | /dryad:DryadDataPackage/dcterms:external | /dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataPackage/dcterms:hasPart | /dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/dryad:DryadDataPackage/dcterms:relation)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'existTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:dabstract) + count(/dryad:DryadDataFile/dcterms:description) + count(/dryad:DryadDataPackage/dcterms:description)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataFile/dwc:scientificName) + count(/dryad:DryadDataPackage/dwc:scientificName)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataFile/dcterms:spatial) + count(/dryad:DryadDataPackage/dcterms:spatial)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataFile/dcterms:temporal) + count(/dryad:*/dcterms:temporal)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadPublication/dcterms:isReferencedBy) + count(/dryad:DryadDataPackage/dcterms:external) + count(/dryad:DryadDataPackage/dcterms:reference) + count(/dryad:DryadDataPackage/dcterms:hasPart) + count(/dryad:DryadDataFile/dcterms:isPartOf)"></xsl:sequence><xsl:sequence select="count(/dryad:DryadDataPackage/dcterms:relation)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'countTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"items" : [
</xsl:text><xsl:text>{
</xsl:text><xsl:text>"name":"Abstract",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists.d1e549" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:dabstract | /dryad:DryadDataFile/dcterms:description | /dryad:DryadDataPackage/dcterms:description)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists.d1e549)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts.d1e549" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:dabstract | /dryad:DryadDataFile/dcterms:description | /dryad:DryadDataPackage/dcterms:description)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts.d1e549)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:dabstract",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:dabstract)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:dabstract)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:description",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:description)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:description)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:description",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:description)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:description)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"This concept is called Desciption in Catalog Services for the Web.",</xsl:text><xsl:text>"description":"A paragraph describing the resource."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Taxonomic Extent",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists.d1e13002" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataFile/dwc:scientificName | /dryad:DryadDataPackage/dwc:scientificName)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists.d1e13002)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts.d1e13002" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataFile/dwc:scientificName | /dryad:DryadDataPackage/dwc:scientificName)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts.d1e13002)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dwc:scientificName",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dwc:scientificName)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dwc:scientificName)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dwc:scientificName",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dwc:scientificName)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dwc:scientificName)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The extent of the taxonomies coverage."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Spatial Extent",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists.d1e7899" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataFile/dcterms:spatial | /dryad:DryadDataPackage/dcterms:spatial)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists.d1e7899)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts.d1e7899" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataFile/dcterms:spatial | /dryad:DryadDataPackage/dcterms:spatial)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts.d1e7899)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:spatial",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:spatial)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:spatial)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:spatial",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:spatial)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:spatial)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The spatial extent of the resource."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Temporal Extent",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists.d1e6524" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataFile/dcterms:temporal | /dryad:*/dcterms:temporal)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists.d1e6524)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts.d1e6524" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataFile/dcterms:temporal | /dryad:*/dcterms:temporal)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts.d1e6524)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:temporal",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:temporal)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:temporal)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:*/dcterms:temporal",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:*/dcterms:temporal)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:*/dcterms:temporal)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The temporal extent of the resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Related Resource Identifier",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists.d1e2829" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadPublication/dcterms:isReferencedBy | /dryad:DryadDataPackage/dcterms:external | /dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataPackage/dcterms:hasPart | /dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists.d1e2829)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts.d1e2829" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadPublication/dcterms:isReferencedBy | /dryad:DryadDataPackage/dcterms:external | /dryad:DryadDataPackage/dcterms:reference | /dryad:DryadDataPackage/dcterms:hasPart | /dryad:DryadDataFile/dcterms:isPartOf)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts.d1e2829)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadPublication/dcterms:isReferencedBy",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadPublication/dcterms:isReferencedBy)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadPublication/dcterms:isReferencedBy)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:external",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:external)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:external)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:reference",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:reference)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:reference)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:hasPart",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:hasPart)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:hasPart)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataFile/dcterms:isPartOf",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataFile/dcterms:isPartOf)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataFile/dcterms:isPartOf)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Identifier for a resource related to the resource being described."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource on-line Link",</xsl:text><xsl:variable name="DMAP-DP_Optional.itemExists.d1e6655" as="xs:integer+"><xsl:sequence select="if(exists(/dryad:DryadDataPackage/dcterms:relation)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemExists.d1e6655)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="DMAP-DP_Optional.itemCounts.d1e6655" as="xs:integer+"><xsl:sequence select="count(/dryad:DryadDataPackage/dcterms:relation)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($DMAP-DP_Optional.itemCounts.d1e6655)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/dryad:DryadDataPackage/dcterms:relation",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/dryad:DryadDataPackage/dcterms:relation)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/dryad:DryadDataPackage/dcterms:relation)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Online link referencing additional information about the resource."</xsl:text><xsl:text>}</xsl:text>
<xsl:text>]
</xsl:text><xsl:text>}</xsl:text><xsl:text>],</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'Record'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="document-uri(.)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'Date'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="current-date()"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"rubricType":"DryadDataPackage",</xsl:text><xsl:text>"rubricVersion":"0.1",</xsl:text><xsl:text>"rubricMax":"16",</xsl:text><xsl:variable name="rubricExists" as="xs:integer+"><xsl:sequence select="$DMAP-DP_Required.itemExists"></xsl:sequence><xsl:sequence select="$DMAP-DP_Optional.itemExists"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'rubricExists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($rubricExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="rubricCounts" as="xs:integer+"><xsl:sequence select="$DMAP-DP_Required.itemCounts"></xsl:sequence><xsl:sequence select="$DMAP-DP_Optional.itemCounts"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'rubricCounts'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="sum($rubricCounts)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text></xsl:template></xsl:stylesheet>