<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:mri="http://www.isotc211.org/namespace/mri/1.0/2014-07-11" xmlns:gex="http://www.isotc211.org/namespace/gex/1.0/2014-07-11" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/" xmlns:echo="http://www.echo.nasa.gov/ingest/schemas/operations/" xmlns:eos="http://earthdata.nasa.gov/schema/eos" xmlns:serf="http://gcmd.gsfc.nasa.gov/xml/serf" xmlns:cw="http://www.ngdc.noaa.gov/metadata/published/xsd/crosswalk.xsd" xmlns:thredds="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0" xmlns:hdf5="http://hdfgroup.org/HDF5/XML/schema/HDF5-File" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:fgdc="http://www.fgdc.gov/metadata/csdgm" version="2.0"><xsl:param name="recordSetPath"></xsl:param><xsl:param name="fileNamePattern"></xsl:param><xsl:output method="text"></xsl:output><xsl:template match="/"><xsl:variable name="xmlFilesSelect" select="concat($recordSetPath, '?select=',$fileNamePattern)"></xsl:variable><xsl:text>{"records": [</xsl:text><xsl:for-each select="collection(iri-to-uri($xmlFilesSelect))"><xsl:call-template name="writeSpirals"></xsl:call-template></xsl:for-each><xsl:text>]}</xsl:text></xsl:template><xsl:template name="writeSpirals"><xsl:if test="position()!=1"><xsl:text>,</xsl:text></xsl:if><xsl:text>{"spirals": [</xsl:text><xsl:text>
{</xsl:text><xsl:text>"title":"Catalog Services for the Web (CSW) Core Queryables",</xsl:text><xsl:text>"code":"CSWCoreQueryables",</xsl:text><xsl:text>"description":"The Open Geospatial Consortium Catalog Services for the Web (CSW) standard defines 11 Core Queryables that must be supported in any compliant implementation. Profiles of CSW map these queryables to concepts and xPaths for particular metadata dialects. For additional reference information see the ISO Profile of CSW (Table 6).",</xsl:text><xsl:text>"maximum":"10",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists" as="xs:integer+"><xsl:sequence select="if(exists(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword | /*/ScienceKeywords/ScienceKeyword/TopicKeyword | /*/ScienceKeywords/ScienceKeyword/TermKeyword | /*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword | /*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/ShortName&gt;/*/LongName)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/Description)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/DataFormat | /*/CSDTDescriptions/CSDTDescription/Implementation | /*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/CollectionAssociations/CollectionAssociation)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'existTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts" as="xs:integer+"><xsl:sequence select="count(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword) + count(/*/ScienceKeywords/ScienceKeyword/TopicKeyword) + count(/*/ScienceKeywords/ScienceKeyword/TermKeyword) + count(/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value) + count(/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value) + count(/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword) + count(/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)"></xsl:sequence><xsl:sequence select="count(/*/ShortName&gt;/*/LongName)"></xsl:sequence><xsl:sequence select="count(/*/Description)"></xsl:sequence><xsl:sequence select="count(/*/DataFormat) + count(/*/CSDTDescriptions/CSDTDescription/Implementation) + count(/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)"></xsl:sequence><xsl:sequence select="count(/*/LastUpdate)"></xsl:sequence><xsl:sequence select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)"></xsl:sequence><xsl:sequence select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem)"></xsl:sequence><xsl:sequence select="count(/*/CollectionAssociations/CollectionAssociation)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'countTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"items" : [
</xsl:text><xsl:text>{
</xsl:text><xsl:text>"name":"Theme Keyword",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e606" as="xs:integer+"><xsl:sequence select="if(exists(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword | /*/ScienceKeywords/ScienceKeyword/TopicKeyword | /*/ScienceKeywords/ScienceKeyword/TermKeyword | /*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword | /*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e606)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e606" as="xs:integer+"><xsl:sequence select="count(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword | /*/ScienceKeywords/ScienceKeyword/TopicKeyword | /*/ScienceKeywords/ScienceKeyword/TermKeyword | /*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword | /*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e606)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/CategoryKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/TopicKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/TopicKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/TopicKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/TermKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/TermKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/TermKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"The general identification keywords usually have a type of theme and are refered to as theme keywords. Other types and vocabularies are used for other information. Service Entry Resource Format (SERF) requires a Science and a Service GCMD Keyword. This concept is called Subject in the CSW Specification. ",</xsl:text><xsl:text>"description":"A word or phrase that describes some aspect of a resource. Can be one of several types."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Title",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e276" as="xs:integer+"><xsl:sequence select="if(exists(/*/ShortName&gt;/*/LongName)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e276)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e276" as="xs:integer+"><xsl:sequence select="count(/*/ShortName&gt;/*/LongName)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e276)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ShortName&gt;/*/LongName",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ShortName&gt;/*/LongName)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ShortName&gt;/*/LongName)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"A short description of the resource. The title should be descriptive enough so that when a user is presented with a list of titles the general content of the data set can be determined."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Abstract",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e484" as="xs:integer+"><xsl:sequence select="if(exists(/*/Description)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e484)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e484" as="xs:integer+"><xsl:sequence select="count(/*/Description)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e484)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Description",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Description)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Description)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"This concept is called Desciption in Catalog Services for the Web.",</xsl:text><xsl:text>"description":"A paragraph describing the resource."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Format",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e4290" as="xs:integer+"><xsl:sequence select="if(exists(/*/DataFormat | /*/CSDTDescriptions/CSDTDescription/Implementation | /*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e4290)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e4290" as="xs:integer+"><xsl:sequence select="count(/*/DataFormat | /*/CSDTDescriptions/CSDTDescription/Implementation | /*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e4290)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/DataFormat",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/DataFormat)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/DataFormat)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/CSDTDescriptions/CSDTDescription/Implementation",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/CSDTDescriptions/CSDTDescription/Implementation)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/CSDTDescriptions/CSDTDescription/Implementation)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The physical or digital manifestation of the resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Metadata Identifier",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"A phrase or string which uniquely identifies the metadata file/record."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Modified Date",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e4053" as="xs:integer+"><xsl:sequence select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e4053)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e4053" as="xs:integer+"><xsl:sequence select="count(/*/LastUpdate)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e4053)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/LastUpdate",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/LastUpdate)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Date on which the record was created or updated within the catalogue"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Type",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"A resource code identifying the type of resource; e.g. dataset, a collection, an application (See MD_ScopeCode) for which the metadata describes."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Bounding Box",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e4093" as="xs:integer+"><xsl:sequence select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e4093)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e4093" as="xs:integer+"><xsl:sequence select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e4093)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"This concept is called Coverage in the CSW Specification",</xsl:text><xsl:text>"description":"A bounding box for identifying a geographic area of interest"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Coordinate Reference System (CRS)",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e4134" as="xs:integer+"><xsl:sequence select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e4134)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e4134" as="xs:integer+"><xsl:sequence select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e4134)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/CoordinateSystem)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Geographic Coordinate Reference System (Authority and ID) for the BoundingBox"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Association",</xsl:text><xsl:variable name="CSWCoreQueryables.itemExists.d1e4178" as="xs:integer+"><xsl:sequence select="if(exists(/*/CollectionAssociations/CollectionAssociation)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemExists.d1e4178)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreQueryables.itemCounts.d1e4178" as="xs:integer+"><xsl:sequence select="count(/*/CollectionAssociations/CollectionAssociation)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreQueryables.itemCounts.d1e4178)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/CollectionAssociations/CollectionAssociation",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/CollectionAssociations/CollectionAssociation)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/CollectionAssociations/CollectionAssociation)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Complete statement of a one-to-one relationship"</xsl:text><xsl:text>}</xsl:text>
<xsl:text>]
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"title":"Catalog Services for the Web (CSW) Core Returnable Properties",</xsl:text><xsl:text>"code":"CSWCoreReturnables",</xsl:text><xsl:text>"description":"The Open Geospatial Consortium Catalog Services for the Web (CSW) standard defines 15 Core Returnables that must be supported in any compliant implementation. Profiles of CSW map these queryables to concepts and xPaths for particular metadata dialects. For additional reference information see the ISO Profile of CSW (Table 9).",</xsl:text><xsl:text>"maximum":"15",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists" as="xs:integer+"><xsl:sequence select="if(exists(/*/ShortName&gt;/*/LongName)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/Contacts/Contact[Role='Data Originator'] | /*/Contacts/Contact[Role='Producer'] | /*/Contacts/Contact[Role='Investigator'] | /*/Contacts/Contact[Role='investigator'] | /*/Contacts/Contact[Role='INVESTIGATOR'])) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword | /*/ScienceKeywords/ScienceKeyword/TopicKeyword | /*/ScienceKeywords/ScienceKeyword/TermKeyword | /*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword | /*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/Description)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/DataFormat | /*/CSDTDescriptions/CSDTDescription/Implementation | /*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input'])) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'existTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts" as="xs:integer+"><xsl:sequence select="count(/*/ShortName&gt;/*/LongName)"></xsl:sequence><xsl:sequence select="count(/*/Contacts/Contact[Role='Data Originator']) + count(/*/Contacts/Contact[Role='Producer']) + count(/*/Contacts/Contact[Role='Investigator']) + count(/*/Contacts/Contact[Role='investigator']) + count(/*/Contacts/Contact[Role='INVESTIGATOR'])"></xsl:sequence><xsl:sequence select="count(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword) + count(/*/ScienceKeywords/ScienceKeyword/TopicKeyword) + count(/*/ScienceKeywords/ScienceKeyword/TermKeyword) + count(/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value) + count(/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value) + count(/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword) + count(/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)"></xsl:sequence><xsl:sequence select="count(/*/Description)"></xsl:sequence><xsl:sequence select="count(/*/LastUpdate)"></xsl:sequence><xsl:sequence select="count(/*/DataFormat) + count(/*/CSDTDescriptions/CSDTDescription/Implementation) + count(/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)"></xsl:sequence><xsl:sequence select="count(/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input'])"></xsl:sequence><xsl:sequence select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'countTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"items" : [
</xsl:text><xsl:text>{
</xsl:text><xsl:text>"name":"Resource Title",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e276" as="xs:integer+"><xsl:sequence select="if(exists(/*/ShortName&gt;/*/LongName)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e276)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e276" as="xs:integer+"><xsl:sequence select="count(/*/ShortName&gt;/*/LongName)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e276)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ShortName&gt;/*/LongName",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ShortName&gt;/*/LongName)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ShortName&gt;/*/LongName)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"A short description of the resource. The title should be descriptive enough so that when a user is presented with a list of titles the general content of the data set can be determined."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Author / Originator",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e3649" as="xs:integer+"><xsl:sequence select="if(exists(/*/Contacts/Contact[Role='Data Originator'] | /*/Contacts/Contact[Role='Producer'] | /*/Contacts/Contact[Role='Investigator'] | /*/Contacts/Contact[Role='investigator'] | /*/Contacts/Contact[Role='INVESTIGATOR'])) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e3649)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e3649" as="xs:integer+"><xsl:sequence select="count(/*/Contacts/Contact[Role='Data Originator'] | /*/Contacts/Contact[Role='Producer'] | /*/Contacts/Contact[Role='Investigator'] | /*/Contacts/Contact[Role='investigator'] | /*/Contacts/Contact[Role='INVESTIGATOR'])"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e3649)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Contacts/Contact[Role='Data Originator']",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Contacts/Contact[Role='Data Originator'])) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Contacts/Contact[Role='Data Originator'])"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Contacts/Contact[Role='Producer']",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Contacts/Contact[Role='Producer'])) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Contacts/Contact[Role='Producer'])"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Contacts/Contact[Role='Investigator']",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Contacts/Contact[Role='Investigator'])) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Contacts/Contact[Role='Investigator'])"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Contacts/Contact[Role='investigator']",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Contacts/Contact[Role='investigator'])) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Contacts/Contact[Role='investigator'])"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Contacts/Contact[Role='INVESTIGATOR']",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Contacts/Contact[Role='INVESTIGATOR'])) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Contacts/Contact[Role='INVESTIGATOR'])"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"In CSW this concept is called Creator",</xsl:text><xsl:text>"description":"The principal author of the resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Theme Keyword",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e606" as="xs:integer+"><xsl:sequence select="if(exists(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword | /*/ScienceKeywords/ScienceKeyword/TopicKeyword | /*/ScienceKeywords/ScienceKeyword/TermKeyword | /*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword | /*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e606)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e606" as="xs:integer+"><xsl:sequence select="count(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword | /*/ScienceKeywords/ScienceKeyword/TopicKeyword | /*/ScienceKeywords/ScienceKeyword/TermKeyword | /*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value | /*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword | /*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e606)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/CategoryKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/CategoryKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/TopicKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/TopicKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/TopicKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/TermKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/TermKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/TermKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/VariableLevel1Keyword/Value)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/VariableLevel2Keyword/Value)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/VariableLevel3Keyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ScienceKeywords/ScienceKeyword/DetailedVariableKeyword)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"The general identification keywords usually have a type of theme and are refered to as theme keywords. Other types and vocabularies are used for other information. Service Entry Resource Format (SERF) requires a Science and a Service GCMD Keyword. This concept is called Subject in the CSW Specification. ",</xsl:text><xsl:text>"description":"A word or phrase that describes some aspect of a resource. Can be one of several types."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Abstract",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e484" as="xs:integer+"><xsl:sequence select="if(exists(/*/Description)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e484)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e484" as="xs:integer+"><xsl:sequence select="count(/*/Description)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e484)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Description",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Description)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Description)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"This concept is called Desciption in Catalog Services for the Web.",</xsl:text><xsl:text>"description":"A paragraph describing the resource."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Publisher",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Publisher of the cited resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Contributor Name",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Contributor to the resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Modified Date",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e4053" as="xs:integer+"><xsl:sequence select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e4053)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e4053" as="xs:integer+"><xsl:sequence select="count(/*/LastUpdate)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e4053)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/LastUpdate",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/LastUpdate)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Date on which the record was created or updated within the catalogue"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Type",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"A resource code identifying the type of resource; e.g. dataset, a collection, an application (See MD_ScopeCode) for which the metadata describes."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Format",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e4290" as="xs:integer+"><xsl:sequence select="if(exists(/*/DataFormat | /*/CSDTDescriptions/CSDTDescription/Implementation | /*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e4290)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e4290" as="xs:integer+"><xsl:sequence select="count(/*/DataFormat | /*/CSDTDescriptions/CSDTDescription/Implementation | /*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e4290)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/DataFormat",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/DataFormat)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/DataFormat)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/CSDTDescriptions/CSDTDescription/Implementation",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/CSDTDescriptions/CSDTDescription/Implementation)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/CSDTDescriptions/CSDTDescription/Implementation)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/AdditionalAttributes/AdditionalAttribute[Name='FileFormat']/Value)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The physical or digital manifestation of the resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Metadata Identifier",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"A phrase or string which uniquely identifies the metadata file/record."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Source Citation",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Reference to the processing input source."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Metadata Language",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Language of the metadata"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Related Resource Citation",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e8276" as="xs:integer+"><xsl:sequence select="if(exists(/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input'])) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e8276)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e8276" as="xs:integer+"><xsl:sequence select="count(/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input'])"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e8276)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input']",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input'])) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/CollectionAssociations/CollectionAssociation[CollectionType!='Input'])"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Citation information about the associated resource."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Bounding Box",</xsl:text><xsl:variable name="CSWCoreReturnables.itemExists.d1e4093" as="xs:integer+"><xsl:sequence select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemExists.d1e4093)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWCoreReturnables.itemCounts.d1e4093" as="xs:integer+"><xsl:sequence select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWCoreReturnables.itemCounts.d1e4093)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Spatial/HorizontalSpatialDomain/Geometry/BoundingRectangle)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"note":"This concept is called Coverage in the CSW Specification",</xsl:text><xsl:text>"description":"A bounding box for identifying a geographic area of interest"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Rights",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Information about rights held in and over the resource"</xsl:text><xsl:text>}</xsl:text>
<xsl:text>]
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"title":"Catalog Service for the Web (CSW) Additional Queryable Properties",</xsl:text><xsl:text>"code":"CSWAdditionalQueryables",</xsl:text><xsl:text>"description":"The Open Geospatial Consortium Catalog Services for the Web (CSW) standard supports 10 Additional Queryable search parameters. Profiles of CSW map these queryables to concepts and xPaths for particular metadata dialects. For additional reference information see the ISO Profile of CSW (Table 10).",</xsl:text><xsl:text>"maximum":"9",</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemExists" as="xs:integer+"><xsl:sequence select="if(exists(/*/InsertTime | /*/LastUpdate)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/InsertTime)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/ArchiveCenter | /*/Contacts/Contact/OrganizationName)) then 1 else 0"></xsl:sequence><xsl:sequence select="if(exists(/*/DataSetId | /*/ShortName | /*/LongName)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'existTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemCounts" as="xs:integer+"><xsl:sequence select="count(/*/InsertTime) + count(/*/LastUpdate)"></xsl:sequence><xsl:sequence select="count(/*/InsertTime)"></xsl:sequence><xsl:sequence select="count(/*/ArchiveCenter) + count(/*/Contacts/Contact/OrganizationName)"></xsl:sequence><xsl:sequence select="count(/*/DataSetId) + count(/*/ShortName | /*/LongName)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'countTotal'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemCounts)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"items" : [
</xsl:text><xsl:text>{
</xsl:text><xsl:text>"name":"Revision Date",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Date of revision of the cited resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Creation/Revision Date",</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemExists.d1e386" as="xs:integer+"><xsl:sequence select="if(exists(/*/InsertTime | /*/LastUpdate)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemExists.d1e386)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemCounts.d1e386" as="xs:integer+"><xsl:sequence select="count(/*/InsertTime | /*/LastUpdate)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemCounts.d1e386)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/InsertTime",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/InsertTime)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/InsertTime)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/LastUpdate",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/LastUpdate)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/LastUpdate)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"The date the resource was created"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Publication Date",</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemExists.d1e1958" as="xs:integer+"><xsl:sequence select="if(exists(/*/InsertTime)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemExists.d1e1958)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemCounts.d1e1958" as="xs:integer+"><xsl:sequence select="count(/*/InsertTime)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemCounts.d1e1958)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/InsertTime",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/InsertTime)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/InsertTime)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Date of publication of the cited resource"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Organization Name",</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemExists.d1e1128" as="xs:integer+"><xsl:sequence select="if(exists(/*/ArchiveCenter | /*/Contacts/Contact/OrganizationName)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemExists.d1e1128)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemCounts.d1e1128" as="xs:integer+"><xsl:sequence select="count(/*/ArchiveCenter | /*/Contacts/Contact/OrganizationName)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemCounts.d1e1128)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ArchiveCenter",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ArchiveCenter)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ArchiveCenter)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/Contacts/Contact/OrganizationName",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/Contacts/Contact/OrganizationName)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/Contacts/Contact/OrganizationName)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Name of the organization"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Security Constraints",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Handling restrictions imposed on the resource or metadata for national security or similar security concerns."</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Metadata Language",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Language of the metadata"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Resource Identifier",</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemExists.d1e2556" as="xs:integer+"><xsl:sequence select="if(exists(/*/DataSetId | /*/ShortName | /*/LongName)) then 1 else 0"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemExists.d1e2556)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="CSWAdditionalQueryables.itemCounts.d1e2556" as="xs:integer+"><xsl:sequence select="count(/*/DataSetId | /*/ShortName | /*/LongName)"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($CSWAdditionalQueryables.itemCounts.d1e2556)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>
"paths" : [
</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/DataSetId",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/DataSetId)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/DataSetId)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>,</xsl:text><xsl:text>
{</xsl:text><xsl:text>"path":"/*/ShortName | /*/LongName",</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'exists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="if(exists(/*/ShortName | /*/LongName)) then 1 else 0"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'count'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="count(/*/ShortName | /*/LongName)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text><xsl:text>],
</xsl:text><xsl:text>"description":"Identifier for the resource described by the metadata"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Parent Identifier",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"A unique identifier for a parent dataset or collection"</xsl:text><xsl:text>}</xsl:text>,
<xsl:text>{
</xsl:text><xsl:text>"name":"Keyword Type",</xsl:text><xsl:text>"exists":"-1",</xsl:text><xsl:text>"count":"-1",</xsl:text><xsl:text>"description":"Methods used to group similar keywords"</xsl:text><xsl:text>}</xsl:text>
<xsl:text>]
</xsl:text><xsl:text>}</xsl:text><xsl:text>],</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'Record'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="document-uri(.)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="'Date'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="current-date()"></xsl:value-of><xsl:text>",
</xsl:text><xsl:text>"rubricType":"CSW",</xsl:text><xsl:text>"rubricVersion":"0.1",</xsl:text><xsl:text>"rubricMax":"34",</xsl:text><xsl:variable name="rubricExists" as="xs:integer+"><xsl:sequence select="$CSWCoreQueryables.itemExists"></xsl:sequence><xsl:sequence select="$CSWCoreReturnables.itemExists"></xsl:sequence><xsl:sequence select="$CSWAdditionalQueryables.itemExists"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'rubricExists'"></xsl:value-of><xsl:text>":"</xsl:text><xsl:value-of select="sum($rubricExists)"></xsl:value-of><xsl:text>",
</xsl:text><xsl:variable name="rubricCounts" as="xs:integer+"><xsl:sequence select="$CSWCoreQueryables.itemCounts"></xsl:sequence><xsl:sequence select="$CSWCoreReturnables.itemCounts"></xsl:sequence><xsl:sequence select="$CSWAdditionalQueryables.itemCounts"></xsl:sequence></xsl:variable><xsl:text>"</xsl:text><xsl:value-of select="'rubricCounts'"></xsl:value-of><xsl:text>"</xsl:text><xsl:text>:</xsl:text><xsl:text>"</xsl:text><xsl:value-of select="sum($rubricCounts)"></xsl:value-of><xsl:text>"
</xsl:text><xsl:text>}</xsl:text></xsl:template></xsl:stylesheet>